/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomCarousel {
        /**
          * Number of images to be displayed in carousel per frame/page
         */
        "imageCountPerFrame": number;
        /**
          * Array of URLs to be used as images in carousel
         */
        "imgURLArray": string[];
        /**
          * Interval in seconds between auto frame/page change
         */
        "rotationTimeInSeconds": number;
    }
    interface CustomFrameSelector {
        "currentFrame": number;
        "frameCount": number;
        "initialFrameIndex": number;
    }
}
declare global {
    interface HTMLCustomCarouselElement extends Components.CustomCarousel, HTMLStencilElement {
    }
    var HTMLCustomCarouselElement: {
        prototype: HTMLCustomCarouselElement;
        new (): HTMLCustomCarouselElement;
    };
    interface HTMLCustomFrameSelectorElement extends Components.CustomFrameSelector, HTMLStencilElement {
    }
    var HTMLCustomFrameSelectorElement: {
        prototype: HTMLCustomFrameSelectorElement;
        new (): HTMLCustomFrameSelectorElement;
    };
    interface HTMLElementTagNameMap {
        "custom-carousel": HTMLCustomCarouselElement;
        "custom-frame-selector": HTMLCustomFrameSelectorElement;
    }
}
declare namespace LocalJSX {
    interface CustomCarousel {
        /**
          * Number of images to be displayed in carousel per frame/page
         */
        "imageCountPerFrame"?: number;
        /**
          * Array of URLs to be used as images in carousel
         */
        "imgURLArray"?: string[];
        /**
          * Interval in seconds between auto frame/page change
         */
        "rotationTimeInSeconds"?: number;
    }
    interface CustomFrameSelector {
        "currentFrame"?: number;
        "frameCount": number;
        "initialFrameIndex"?: number;
        "onFrameChange"?: (event: CustomEvent<number>) => void;
    }
    interface IntrinsicElements {
        "custom-carousel": CustomCarousel;
        "custom-frame-selector": CustomFrameSelector;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-carousel": LocalJSX.CustomCarousel & JSXBase.HTMLAttributes<HTMLCustomCarouselElement>;
            "custom-frame-selector": LocalJSX.CustomFrameSelector & JSXBase.HTMLAttributes<HTMLCustomFrameSelectorElement>;
        }
    }
}
